/**
 * Top 100 Google Fonts by popularity.
 * Each entry generates a CSS2 URL with common weights (300–700).
 */

export interface GoogleFontEntry {
  name: string
  category: 'sans-serif' | 'serif' | 'display' | 'handwriting' | 'monospace'
}

export const GOOGLE_FONTS_TOP_100: GoogleFontEntry[] = [
  { name: 'Roboto', category: 'sans-serif' },
  { name: 'Open Sans', category: 'sans-serif' },
  { name: 'Noto Sans', category: 'sans-serif' },
  { name: 'Montserrat', category: 'sans-serif' },
  { name: 'Lato', category: 'sans-serif' },
  { name: 'Poppins', category: 'sans-serif' },
  { name: 'Roboto Condensed', category: 'sans-serif' },
  { name: 'Inter', category: 'sans-serif' },
  { name: 'Oswald', category: 'sans-serif' },
  { name: 'Roboto Mono', category: 'monospace' },
  { name: 'Raleway', category: 'sans-serif' },
  { name: 'Noto Sans JP', category: 'sans-serif' },
  { name: 'Ubuntu', category: 'sans-serif' },
  { name: 'Nunito', category: 'sans-serif' },
  { name: 'Roboto Slab', category: 'serif' },
  { name: 'Nunito Sans', category: 'sans-serif' },
  { name: 'Playfair Display', category: 'serif' },
  { name: 'Merriweather', category: 'serif' },
  { name: 'Rubik', category: 'sans-serif' },
  { name: 'PT Sans', category: 'sans-serif' },
  { name: 'Kanit', category: 'sans-serif' },
  { name: 'Work Sans', category: 'sans-serif' },
  { name: 'Lora', category: 'serif' },
  { name: 'Noto Sans KR', category: 'sans-serif' },
  { name: 'Fira Sans', category: 'sans-serif' },
  { name: 'Quicksand', category: 'sans-serif' },
  { name: 'Barlow', category: 'sans-serif' },
  { name: 'Mulish', category: 'sans-serif' },
  { name: 'IBM Plex Sans', category: 'sans-serif' },
  { name: 'Noto Sans TC', category: 'sans-serif' },
  { name: 'PT Serif', category: 'serif' },
  { name: 'Inconsolata', category: 'monospace' },
  { name: 'Titillium Web', category: 'sans-serif' },
  { name: 'Heebo', category: 'sans-serif' },
  { name: 'Manrope', category: 'sans-serif' },
  { name: 'Libre Franklin', category: 'sans-serif' },
  { name: 'Noto Serif', category: 'serif' },
  { name: 'Karla', category: 'sans-serif' },
  { name: 'Josefin Sans', category: 'sans-serif' },
  { name: 'DM Sans', category: 'sans-serif' },
  { name: 'Libre Baskerville', category: 'serif' },
  { name: 'Arimo', category: 'sans-serif' },
  { name: 'Source Code Pro', category: 'monospace' },
  { name: 'Cabin', category: 'sans-serif' },
  { name: 'Dosis', category: 'sans-serif' },
  { name: 'Bitter', category: 'serif' },
  { name: 'Hind', category: 'sans-serif' },
  { name: 'Anton', category: 'sans-serif' },
  { name: 'Oxygen', category: 'sans-serif' },
  { name: 'Mukta', category: 'sans-serif' },
  { name: 'Source Sans 3', category: 'sans-serif' },
  { name: 'Bebas Neue', category: 'sans-serif' },
  { name: 'Abel', category: 'sans-serif' },
  { name: 'Archivo', category: 'sans-serif' },
  { name: 'Jost', category: 'sans-serif' },
  { name: 'Exo 2', category: 'sans-serif' },
  { name: 'Fjalla One', category: 'sans-serif' },
  { name: 'Comfortaa', category: 'display' },
  { name: 'Varela Round', category: 'sans-serif' },
  { name: 'Overpass', category: 'sans-serif' },
  { name: 'Signika Negative', category: 'sans-serif' },
  { name: 'Noto Sans SC', category: 'sans-serif' },
  { name: 'Maven Pro', category: 'sans-serif' },
  { name: 'Barlow Condensed', category: 'sans-serif' },
  { name: 'Catamaran', category: 'sans-serif' },
  { name: 'Teko', category: 'sans-serif' },
  { name: 'IBM Plex Mono', category: 'monospace' },
  { name: 'Pacifico', category: 'handwriting' },
  { name: 'Crimson Text', category: 'serif' },
  { name: 'Assistant', category: 'sans-serif' },
  { name: 'Cormorant Garamond', category: 'serif' },
  { name: 'Prompt', category: 'sans-serif' },
  { name: 'Space Grotesk', category: 'sans-serif' },
  { name: 'Dancing Script', category: 'handwriting' },
  { name: 'Archivo Narrow', category: 'sans-serif' },
  { name: 'Red Hat Display', category: 'sans-serif' },
  { name: 'EB Garamond', category: 'serif' },
  { name: 'Lobster', category: 'display' },
  { name: 'Asap', category: 'sans-serif' },
  { name: 'Rajdhani', category: 'sans-serif' },
  { name: 'Outfit', category: 'sans-serif' },
  { name: 'Satisfy', category: 'handwriting' },
  { name: 'Nanum Gothic', category: 'sans-serif' },
  { name: 'Signika', category: 'sans-serif' },
  { name: 'Encode Sans', category: 'sans-serif' },
  { name: 'Shadows Into Light', category: 'handwriting' },
  { name: 'Abril Fatface', category: 'display' },
  { name: 'Lexend', category: 'sans-serif' },
  { name: 'Secular One', category: 'sans-serif' },
  { name: 'Saira Condensed', category: 'sans-serif' },
  { name: 'Public Sans', category: 'sans-serif' },
  { name: 'Yanone Kaffeesatz', category: 'sans-serif' },
  { name: 'Indie Flower', category: 'handwriting' },
  { name: 'Permanent Marker', category: 'handwriting' },
  { name: 'Figtree', category: 'sans-serif' },
  { name: 'Plus Jakarta Sans', category: 'sans-serif' },
  { name: 'Righteous', category: 'display' },
  { name: 'Zilla Slab', category: 'serif' },
  { name: 'Urbanist', category: 'sans-serif' },
]

/**
 * Build a Google Fonts CSS2 URL for a given font name with common weights.
 */
export function buildGoogleFontUrl(name: string): string {
  const family = name.replace(/ /g, '+')
  return `https://fonts.googleapis.com/css2?family=${family}:wght@300;400;500;600;700&display=swap`
}
